baseURL                = "http://localhost:4002/"
languageCode           = "en-us"
title                  = "Robin Su"
defaultContentLanguage = "en"
hasCJKLanguage         = true
theme                  = "hugo-theme-stack"
timeZone               = "Asia/Shanghai"

[pagination]
    pagerSize = 10

[permalinks]
    post = "/p/:slug/"
    page = "/:slug/"

[outputs]
    home = ["HTML", "RSS", "JSON"]
