[en]
    languageName = "English"
    title        = "Robin's Space"
    weight       = 1

    [en.params.sidebar]
        emoji    = "🚀"
        subtitle = "AWS Solutions Architect | Cloud & AI"
        avatar   = "img/avatar.png"

[zh]
    languageName = "简体中文"
    title        = "Robin's Space"
    weight       = 2

    [zh.params.sidebar]
        emoji    = "🚀"
        subtitle = "AWS 解决方案架构师 | 云计算 & AI"
        avatar   = "img/avatar.png"
