[[main]]
    identifier = "about"
    name       = "About"
    url        = "/about/"
    weight     = -100
    [main.params]
        icon = "user"

[[main]]
    identifier = "tech"
    name       = "Blog"
    url        = "/"
    weight     = -90
    [main.params]
        icon = "messages"

[[main]]
    identifier = "projects"
    name       = "Projects"
    url        = "/projects/"
    weight     = -80
    [main.params]
        icon = "code"

[[social]]
    identifier = "github"
    name       = "GitHub"
    url        = "https://github.com/robinsujob"
        weight = 1
    [social.params]
        icon = "brand-github"
        newTab = true

[[social]]
    identifier = "linkedin"
    name       = "LinkedIn"
    url        = "https://www.linkedin.com/in/robin-su/"
        weight = 2
    [social.params]
        icon = "brand-linkedin"
        newTab = true

[[social]]
    identifier = "instagram"
    name       = "Instagram"
    url        = "https://www.instagram.com/robinsu77/"
        weight = 3
    [social.params]
        icon = "brand-instagram"
        newTab = true

[[social]]
    identifier = "email"
    name       = "Email"
    url        = "mailto:robinsujob@outlook.com"
    weight     = 4
    [social.params]
        icon = "mail"
        newTab = true
