[[main]]
    identifier = "home"
    name       = "Home"
    url        = "/"
    weight     = -100
    [main.params]
        icon = "home"

[[main]]
    identifier = "projects"
    name       = "Projects"
    url        = "/page/projects/"
    weight     = -90
    [main.params]
        icon = "link"

[[main]]
    identifier = "photography"
    name       = "Photography"
    url        = "/categories/photography/"
    weight     = -80
    [main.params]
        icon = "infinity"

[[social]]
    identifier = "github"
    name       = "GitHub"
    url        = "https://github.com/"
    [social.params]
        icon = "brand-github"
