[[main]]
    identifier = "home"
    name       = "首页"
    url        = "/zh/"
    weight     = -100
    [main.params]
        icon = "home"

[[main]]
    identifier = "about"
    name       = "关于"
    url        = "/zh/about/"
    weight     = -95
    [main.params]
        icon = "user"

[[main]]
    identifier = "projects"
    name       = "项目"
    url        = "/zh/projects/"
    weight     = -90
    [main.params]
        icon = "link"

[[main]]
    identifier = "photography"
    name       = "摄影"
    url        = "/zh/categories/photography/"
    weight     = -80
    [main.params]
        icon = "infinity"

[[social]]
    identifier = "github"
    name       = "GitHub"
    url        = "https://github.com/"
    [social.params]
        icon = "brand-github"
