[[main]]
    identifier = "about"
    name       = "About"
    url        = "/about/"
    weight     = -100
    [main.params]
        icon = "user"

[[main]]
    identifier = "tech"
    name       = "Tech"
    url        = "/"
    weight     = -90
    [main.params]
        icon = "home"

[[main]]
    identifier = "projects"
    name       = "Projects"
    url        = "/projects/"
    weight     = -80
    [main.params]
        icon = "link"

[[main]]
    identifier = "photography"
    name       = "Photography"
    url        = "/categories/photography/"
    weight     = -70
    [main.params]
        icon = "infinity"

[[social]]
    identifier = "github"
    name       = "GitHub"
    url        = "https://github.com/"
    [social.params]
        icon = "brand-github"
