[[main]]
    identifier = "about"
    name       = "关于"
    url        = "/zh/about/"
    weight     = -100
    [main.params]
        icon = "user"

[[main]]
    identifier = "tech"
    name       = "技术"
    url        = "/zh/"
    weight     = -90
    [main.params]
        icon = "code"

[[main]]
    identifier = "projects"
    name       = "项目"
    url        = "/zh/projects/"
    weight     = -80
    [main.params]
        icon = "link"

[[social]]
    identifier = "github"
    name       = "GitHub"
    url        = "https://github.com/robinsujob"
    [social.params]
        icon = "brand-github"

[[social]]
    identifier = "linkedin"
    name       = "LinkedIn"
    url        = "https://www.linkedin.com/in/robin-su/"
    [social.params]
        icon = "brand-linkedin"

[[social]]
    identifier = "instagram"
    name       = "Instagram"
    url        = "https://www.instagram.com/robinsu77/"
    [social.params]
        icon = "brand-instagram"
