mainSections   = ["post"]
rssFullContent = true
favicon        = "/favicon.ico"

[footer]
    since = 2023

[sidebar]
    emoji    = ""
    avatar   = "img/avatar.png"

[article]
    toc         = true
    readingTime = true

    [article.license]

[widgets]
    homepage = [
        { type = "search" },
        { type = "archives", params = { limit = 5 } },
        { type = "categories", params = { limit = 10 } },
        { type = "tag-cloud", params = { limit = 10 } },
    ]
    page = [{ type = "toc" }]

[comments]
    enabled  = true
    provider = "giscus"

[colorScheme]
    toggle  = true
    default = "auto"

[comments.giscus]
    repo             = "robinsujob/robinsujob.github.io"
    repoID           = "R_kgDOR6InNQ"
    category         = "Announcements"
    categoryID       = "DIC_kwDOR6InNc4C6Fgx"
    mapping          = "pathname"
    strict           = 0
    reactionsEnabled = 1
    emitMetadata     = 0
    inputPosition    = "bottom"
    lightTheme       = "light"
    darkTheme        = "dark_dimmed"
    lang             = "en"
    loading          = "lazy"
